version: '3.8'

services:
  backend:
    build: .
    image: kurigohan73/backend:latest
    container_name: backend
    restart: unless-stopped
    environment:
      DATABASE_HOST: seonlim.c7muuq84guhv.ap-northeast-2.rds.amazonaws.com
      DATABASE_USER: makisekurisu
      DATABASE_PASSWORD: elpsycongroo
      DATABASE_NAME: SteinsGate
      DATABASE_PORT: 3306
    ports:
      - "3000:3000"
#    volumes:
#      - /home/ec2-user/keys/fullchain.pem:/etc/ssl/certs/fullchain.pem
#      - /home/ec2-user/keys/privkey.pem:/etc/ssl/private/privkey.pem
    networks:
      - app-network

networks:
  app-network:
    driver: bridge