on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key for Public EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > nestjs-cotept.pem
          chmod 600 nestjs-cotept.pem
          echo "SSH Key Created:"
          ls -la nestjs-cotept.pem  # 파일의 권한과 존재 여부를 확인
          echo "SSH Key Content:"
          head -n 5 nestjs-cotept.pem  # 키 내용의 일부만 출력 (보안상 이유로 일부만 출력)

      - name: Copy PEM key to Public EC2
        run: |
          scp -o StrictHostKeyChecking=no -i nestjs-cotept.pem nestjs-cotept.pem ubuntu@${{ secrets.PUBLIC_EC2_IP }}:/home/ubuntu/.ssh/nestjs-cotept.pem
          ssh -o StrictHostKeyChecking=no -i nestjs-cotept.pem ubuntu@${{ secrets.PUBLIC_EC2_IP }} "chmod 600 /home/ubuntu/.ssh/nestjs-cotept.pem"

      - name: Set up project directory on EC2
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i nestjs-cotept.pem -J ubuntu@${{ secrets.PUBLIC_EC2_IP }} ec2-user@${{ secrets.PRIVATE_EC2_IP }} << 'EOF'
            mkdir -p ~/project-root
            chown $USER:$USER ~/project-root
            chmod 755 ~/project-root
          cp /home/ubuntu/project-root/nestjs-cotept.pem /home/ec2-user/nestjs-cotept.pem
            chmod 600 /home/ec2-user/nestjs-cotept.pem
          EOF

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -J ubuntu@${{ secrets.PUBLIC_EC2_IP }} -i nestjs-cotept.pem -o StrictHostKeyChecking=no" --exclude='node_modules' --exclude='.git' --exclude='.gitignore' ./ ec2-user@${{ secrets.PRIVATE_EC2_IP }}:~/project-root

      - name: Deploy on EC2
        run: |
          ssh -tt -o ForwardAgent=yes -o StrictHostKeyChecking=no -i nestjs-cotept.pem -J ubuntu@${{ secrets.PUBLIC_EC2_IP }} ec2-user@${{ secrets.PRIVATE_EC2_IP }} << EOF
            cd ~/project-root
            docker-compose down || true
            docker-compose up -d --build
          EOF
