name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 배포 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI and Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          pip install --upgrade awsebcli

      - name: Build Docker image
        run: |
          sudo docker build --no-cache -t seonlim .

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 990359324762.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Tag Docker image
        run: |
          docker tag seonlim:latest 990359324762.dkr.ecr.ap-northeast-2.amazonaws.com/seonlim:${{ github.sha }}

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 990359324762.dkr.ecr.ap-northeast-2.amazonaws.com/seonlim:${{ github.sha }}

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p docker seonlim --region ap-northeast-2
          eb use Elpsycongroo-env
          eb setenv DEPLOY_TIMESTAMP=$(date +%s)
          eb deploy --staged

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
