name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > aikey.pem
          chmod 400 aikey.pem

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i aikey.pem -r . $${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_IP }}:~/project-root

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i aikey.pem $EC2_USER@$AWS_EC2_IP << 'EOF'
            cd ~/project-root
            docker-compose down || true
            docker-compose up -d --build
          EOF
